// Generated by gencpp from file programmerings_projekt/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PROGRAMMERINGS_PROJEKT_MESSAGE_ADDTWOINTS_H
#define PROGRAMMERINGS_PROJEKT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <programmerings_projekt/AddTwoIntsRequest.h>
#include <programmerings_projekt/AddTwoIntsResponse.h>


namespace programmerings_projekt
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace programmerings_projekt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::programmerings_projekt::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::programmerings_projekt::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::programmerings_projekt::AddTwoInts > {
  static const char* value()
  {
    return "programmerings_projekt/AddTwoInts";
  }

  static const char* value(const ::programmerings_projekt::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::programmerings_projekt::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::programmerings_projekt::AddTwoInts > 
template<>
struct MD5Sum< ::programmerings_projekt::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::programmerings_projekt::AddTwoInts >::value();
  }
  static const char* value(const ::programmerings_projekt::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::programmerings_projekt::AddTwoIntsRequest> should match 
// service_traits::DataType< ::programmerings_projekt::AddTwoInts > 
template<>
struct DataType< ::programmerings_projekt::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::programmerings_projekt::AddTwoInts >::value();
  }
  static const char* value(const ::programmerings_projekt::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::programmerings_projekt::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::programmerings_projekt::AddTwoInts > 
template<>
struct MD5Sum< ::programmerings_projekt::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::programmerings_projekt::AddTwoInts >::value();
  }
  static const char* value(const ::programmerings_projekt::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::programmerings_projekt::AddTwoIntsResponse> should match 
// service_traits::DataType< ::programmerings_projekt::AddTwoInts > 
template<>
struct DataType< ::programmerings_projekt::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::programmerings_projekt::AddTwoInts >::value();
  }
  static const char* value(const ::programmerings_projekt::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROGRAMMERINGS_PROJEKT_MESSAGE_ADDTWOINTS_H
