// Generated by gencpp from file programmerings_projekt/Num.msg
// DO NOT EDIT!


#ifndef PROGRAMMERINGS_PROJEKT_MESSAGE_NUM_H
#define PROGRAMMERINGS_PROJEKT_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace programmerings_projekt
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : pointarray()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : pointarray(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _pointarray_type;
  _pointarray_type pointarray;





  typedef boost::shared_ptr< ::programmerings_projekt::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::programmerings_projekt::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::programmerings_projekt::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::programmerings_projekt::Num > NumPtr;
typedef boost::shared_ptr< ::programmerings_projekt::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::programmerings_projekt::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::programmerings_projekt::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace programmerings_projekt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'programmerings_projekt': ['/home/ros/Programmering/src/programmerings_projekt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::programmerings_projekt::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::programmerings_projekt::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::programmerings_projekt::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::programmerings_projekt::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::programmerings_projekt::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::programmerings_projekt::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::programmerings_projekt::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bba95aca27ea6460037613bb86c57c0";
  }

  static const char* value(const ::programmerings_projekt::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bba95aca27ea646ULL;
  static const uint64_t static_value2 = 0x0037613bb86c57c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::programmerings_projekt::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "programmerings_projekt/Num";
  }

  static const char* value(const ::programmerings_projekt::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::programmerings_projekt::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] pointarray\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::programmerings_projekt::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::programmerings_projekt::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointarray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::programmerings_projekt::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::programmerings_projekt::Num_<ContainerAllocator>& v)
  {
    s << indent << "pointarray[]" << std::endl;
    for (size_t i = 0; i < v.pointarray.size(); ++i)
    {
      s << indent << "  pointarray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.pointarray[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROGRAMMERINGS_PROJEKT_MESSAGE_NUM_H
